proyecto/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
//rutas para el recurso Aprendiz
Route::resource('aprendiz','AprendizController');
//una nueva ruta para eliminar registros con el metodo get
Route::get('aprendiz/destroy/{id}', ['as' => 'aprendiz/destroy', 'uses'=>'AprendizController@destroy']);
//ruta para realizar busqueda de registros.
Route::post('aprendiz/search', ['as' => 'aprendiz/search', 'uses'=>'AprendizController@search']);
//ruta para realizar actualizacion de registros.
Route::post('aprendiz/update', ['as' => 'aprendiz/update', 'uses'=>'AprendizController@update']);
//rutas para el recurso Profesor
Route::resource('profesor','ProfesorController');
//una nueva ruta para eliminar registros con el metodo get
Route::get('profesor/destroy/{id}', ['as' => 'profesor/destroy', 'uses'=>'ProfesorController@destroy']);
//ruta para realizar busqueda de registros.
Route::post('profesor/search', ['as' => 'profesor/search', 'uses'=>'ProfesorController@search']);
//ruta para realizar actualizacion de registros.
Route::post('profesor/update', ['as' => 'profesor/update', 'uses'=>'ProfesorController@update']);
//rutas para el recurso Acta reunion
Route::resource('actareunion','ActareunionController');
//una nueva ruta para eliminar registros con el metodo get
Route::get('actareunion/destroy/{id}', ['as' => 'actareunion/destroy', 'uses'=>'ActareunionController@destroy']);
//ruta para realizar busqueda de registros.
Route::post('actareunion/search', ['as' => 'actareunion/search', 'uses'=>'ActareunionController@search']);
//ruta para realizar actualizacion de registros.
Route::post('actareunion/update', ['as' => 'actareunion/update', 'uses'=>'ActareunionController@update']);

proyecto/resources/views/acta reunion/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="row">
		<section class="col-md-10 col-md-offset-1">
			{!! Form::open(['route' => 'actareunion/search', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
				<article class="form-group">
					<label for="exampleInputName2">BUSCAR POR NOMBRE</label>
					<input type="text" class="form-control" name = "fecha" >
					<button type="submit" class="btn btn-default glyphicon glyphicon-search"></button>
					<a href="{{ route('actareunion.index') }}" class="btn btn-primary">MOSTRAR TODO</a>
					<a href="{{ route('actareunion.create') }}" class="btn btn-primary">CREAR NUEVO REGISTRO </a>
				</article>
			{!! Form::close() !!}
			<article class="form-group">
				<table class="table table-bordered">
					<tr>
						<th>fecha</th>
						<th>hora de inicio</th>
						<th>hora  de finalizacion</th>
						<th>proyecto</th>
						<th>asunto</th>
						<th>asistentes</th>
						<th>asistentes externos</th>
						<th>elaborado por</th>
						<th>proxima reunion</th>
						<th>descripcion reunion</th>
						
					</tr>
					<tbody>

						@foreach($actareunions as $actareunion)
							<tr>
								<td>{{ $actareunion->fecha}}</td>
								<td>{{ $actareunion->horainicio}}</td>
								<td>{{ $actareunion->horafinal}}</td>
								<td>{{ $actareunion->lugar}}</td>
								<td>{{ $actareunion->proyecto}}</td>
								<td>{{ $actareunion->asunto}}</td>
								<td>{{ $actareunion->asistentes}}</td>
								<td>{{ $actareunion->asistentesexternos}}</td>
								<td>{{ $actareunion->elaboradopor}}</td>
								<td>{{ $actareunion->proximareunion}}</td>
								<td>{{ $actareunion->descripionreunion}}</td>
								
								<td>
									<a class="btn btn-primary btn-xs" href="{{ route('actareunion.edit',['id' => $actareunion->id] )}}" >EDITAR</a>
									<a class="btn btn-danger btn-xs" href="{{ route('actareunion/destroy',['id' => $actareunion->id] )}}">ARCHIVAR</a>
								</td>
							</tr>
						@endforeach

					</tbody>
				</table>
			</article>
		</section>
	</section>
@endsection

proyecto/resources/views/acta reunion/new.blade.php
@extends('layouts.app')
@section('content')
<section class="container">
	<section class="row">
		<article class="col-md-10 col-md-offset-1">
			{!! Form::open(['route' => 'actareunion.store', 'method' => 'post', 'novalidate']) !!}
				<section class="form-group">
					{!! Form::label('fecha', 'fecha') !!}
					{!! Form::text('fecha', null, ['id' => 'nombre','class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('horainicio', 'horainicio') !!}
					{!! Form::text('horainicio', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('horafinal', 'horafinal') !!}
					{!! Form::text('horafinal', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('lugar', 'lugar') !!}
					{!! Form::text('lugar', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('proyecto', 'proyecto') !!}
					{!! Form::text('proyecto', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('asunto', 'asunto') !!}
					{!! Form::text('asunto', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('asistentes', 'asistentes') !!}
					{!! Form::text('asistentes', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('asistentesexternos', 'asistentesexternos') !!}
					{!! Form::text('asistentesexternos', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('elaboradopor', 'elaboradopor') !!}
					{!! Form::text('elaboradopor', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('proximareunion', 'proximareunion') !!}
					{!! Form::text('proximareunion', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('descripcionreunion', 'descripcionreunion') !!}
					{!! Form::text('descripcionreunion', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::submit('Enviar', ['class' => 'btn btn-succes ' ] ) !!}
				</section>
			{!! Form::close() !!}
		</article>
	</section>
</section>
@endsection

proyecto/resources/views/acta reunion/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="row">
		<section class="col-md-10 col-md-offset-1">
				{!! Form::model($actareunion, ['route' => 'actareunion/update', 'method' => 'put', 'novalidate']) !!}
						{!! Form::hidden('id', $actareunion->id) !!}
						<article class="form-group">
							{!! Form::label('fecha', 'fecha') !!}
							{!! Form::text('fecha', null, ['class' => 'form-control', 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('horainicio', 'horainicio') !!}
							{!! Form::text('horainicio', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('horafinal', 'horafinal') !!}
							{!! Form::text('horafinal', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('lugar', 'lugar') !!}
							{!! Form::text('lugar', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('proyecto', 'proyecto') !!}
							{!! Form::text('proyecto', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('asistentes', 'asistentes') !!}
							{!! Form::text('asistentes', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('asistentesexternos', 'asistentesexternos') !!}
							{!! Form::text('asistentesexternos', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('elaboradopor', 'elaboradopor') !!}
							{!! Form::text('elaboradopor', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('proximareunion', 'proximareunion') !!}
							{!! Form::text('proximareunion', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('descripcionreunion', 'descripcionreunioon') !!}
							{!! Form::text('descripcionreunion', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						
						<article class="form-group">
							{!! Form::submit('Enviar', null, ['class' => 'btn btn-success']) !!}
						</article>
				 {!! Form::close() !!}
		</section>
	</section>
@endsection