proyecto/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
//rutas para el recurso Aprendiz
Route::resource('aprendiz','AprendizController');
//una nueva ruta para eliminar registros con el metodo get
Route::get('aprendiz/destroy/{id}', ['as' => 'aprendiz/destroy', 'uses'=>'AprendizController@destroy']);
//ruta para realizar busqueda de registros.
Route::post('aprendiz/search', ['as' => 'aprendiz/search', 'uses'=>'AprendizController@search']);
//ruta para realizar actualizacion de registros.
Route::post('aprendiz/update', ['as' => 'aprendiz/update', 'uses'=>'AprendizController@update']);
//rutas para el recurso Profesor
Route::resource('profesor','ProfesorController');
//una nueva ruta para eliminar registros con el metodo get
Route::get('profesor/destroy/{id}', ['as' => 'profesor/destroy', 'uses'=>'ProfesorController@destroy']);
//ruta para realizar busqueda de registros.
Route::post('profesor/search', ['as' => 'profesor/search', 'uses'=>'ProfesorController@search']);
//ruta para realizar actualizacion de registros.
Route::post('profesor/update', ['as' => 'profesor/update', 'uses'=>'ProfesorController@update']);
//rutas para el recurso Acta reunion
Route::resource('actareunion','ActareunionController');
//una nueva ruta para eliminar registros con el metodo get
Route::get('actareunion/destroy/{id}', ['as' => 'actareunion/destroy', 'uses'=>'ActareunionController@destroy']);
//ruta para realizar busqueda de registros.
Route::post('actareunion/search', ['as' => 'actareunion/search', 'uses'=>'ActareunionController@search']);
//ruta para realizar actualizacion de registros.
Route::post('actareunion/update', ['as' => 'actareunion/update', 'uses'=>'ActareunionController@update']);

proyecto/app/Models/Profesor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Profesor extends Model
{
     protected $table = 'profesors';
  protected $fillable = ['nombre', 'apellido', 'documento', 'genero'];
  protected $guarded = ['id'];
}

proyecto/app/Http/Controllers/ProfesorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Profesor as Profesor;

use Illuminate\Http\Request;

use App\Http\Requests;

class ProfesorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $profesors = Profesor::all();
        return \View::make('profesor/list',compact('profesors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return \View::make('profesor/new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $profesor = new Profesor;
       $profesor->nombre = $request->nombre;
       $profesor->apellido = $request->apellido;
       $profesor->documento = $request->documento;
       $profesor->genero = $request->genero;
       $profesor->save();
       return redirect('profesor');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $profesor = Profesor::find($id);
        return \View::make('profesor/update',compact('profesor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $profesor = Profesor::find($request->id);
        $profesor->nombre = $request->nombre;
        $profesor->apellido = $request->apellido;
        $profesor->documento = $request->documento;
        $profesor->genero = $request->genero;
        $profesor->save();
        return redirect('profesor');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $profesor = Profesor::find($id);
        $profesor->delete();
        return redirect()->back();
    }
    public function search(Request $request)
    {

    
      $profesors = Profesor::where('nombre','=',$request->nombre)       
        ->get();
       return \View::make('profesor/list',compact('profesors'));
   }
}

proyecto/resources/views/profesor/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="row">
		<section class="col-md-10 col-md-offset-1">
			{!! Form::open(['route' => 'profesor/search', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
				<article class="form-group">
					<label for="exampleInputName2">BUSCAR POR NOMBRE</label>
					<input type="text" class="form-control" name = "nombre" >
					<button type="submit" class="btn btn-default glyphicon glyphicon-search"></button>
					<a href="{{ route('profesor.index') }}" class="btn btn-primary">MOSTRAR TODO</a>
					<a href="{{ route('profesor.create') }}" class="btn btn-primary">CREAR NUEVO REGISTRO </a>
				</article>
			{!! Form::close() !!}
			<article class="form-group">
				<table class="table table-bordered">
					<tr>
						<th>nombres del profesor</th>
						<th>apellidos del profesor</th>
						<th>documento</th>
						<th>genero</th>
					</tr>
					<tbody>

						@foreach($profesors as $profesor)
							<tr>
								<td>{{ $profesor->nombre}}</td>
								<td>{{ $profesor->apellido}}</td>
								<td>{{ $profesor->documento}}</td>
								<td>{{ $profesor->genero}}</td>
								<td>
									<a class="btn btn-primary btn-xs" href="{{ route('profesor.edit',['id' => $profesor->id] )}}" >EDITAR</a>
									<a class="btn btn-danger btn-xs" href="{{ route('profesor/destroy',['id' => $profesor->id] )}}">ARCHIVAR</a>
								</td>
							</tr>
						@endforeach

					</tbody>
				</table>
			</article>
		</section>
	</section>
@endsection

proyecto/resources/views/profesor/new.blade.php
@extends('layouts.app')
@section('content')
<section class="container">
	<section class="row">
		<article class="col-md-10 col-md-offset-1">
			{!! Form::open(['route' => 'profesor.store', 'method' => 'post', 'novalidate']) !!}
				<section class="form-group">
					{!! Form::label('nombre', 'nombre') !!}
					{!! Form::text('nombre', null, ['id' => 'nombre','class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('apellido', 'apellido') !!}
					{!! Form::text('apellido', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('documento', 'documento') !!}
					{!! Form::text('documento', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('genero', 'genero') !!}
					{!! Form::text('genero', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::submit('Enviar', ['class' => 'btn btn-succes ' ] ) !!}
				</section>
			{!! Form::close() !!}
		</article>
	</section>
</section>
@endsection

proyecto/resources/views/profesor/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="row">
		<section class="col-md-10 col-md-offset-1">
				{!! Form::model($profesor, ['route' => 'profesor/update', 'method' => 'put', 'novalidate']) !!}
						{!! Form::hidden('id', $profesor->id) !!}
						<article class="form-group">
							{!! Form::label('nombre', 'nombre') !!}
							{!! Form::text('nombre', null, ['class' => 'form-control', 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('apellido', 'apellido') !!}
							{!! Form::text('apellido', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('documento', 'documento') !!}
							{!! Form::text('documento', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('genero', 'genero') !!}
							{!! Form::text('genero', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::submit('Enviar', null, ['class' => 'btn btn-success']) !!}
						</article>
				 {!! Form::close() !!}
		</section>
	</section>
@endsection