proyecto/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
//rutas para el recurso Aprendiz
Route::resource('aprendiz','AprendizController');
//una nueva ruta para eliminar registros con el metodo get
Route::get('aprendiz/destroy/{id}', ['as' => 'aprendiz/destroy', 'uses'=>'AprendizController@destroy']);
//ruta para realizar busqueda de registros.
Route::post('aprendiz/search', ['as' => 'aprendiz/search', 'uses'=>'AprendizController@search']);
//ruta para realizar actualizacion de registros.
Route::post('aprendiz/update', ['as' => 'aprendiz/update', 'uses'=>'AprendizController@update']);
//rutas para el recurso Profesor
Route::resource('profesor','ProfesorController');
//una nueva ruta para eliminar registros con el metodo get
Route::get('profesor/destroy/{id}', ['as' => 'profesor/destroy', 'uses'=>'ProfesorController@destroy']);
//ruta para realizar busqueda de registros.
Route::post('profesor/search', ['as' => 'profesor/search', 'uses'=>'ProfesorController@search']);
//ruta para realizar actualizacion de registros.
Route::post('profesor/update', ['as' => 'profesor/update', 'uses'=>'ProfesorController@update']);
//rutas para el recurso Acta reunion
Route::resource('actareunion','ActareunionController');
//una nueva ruta para eliminar registros con el metodo get
Route::get('actareunion/destroy/{id}', ['as' => 'actareunion/destroy', 'uses'=>'ActareunionController@destroy']);
//ruta para realizar busqueda de registros.
Route::post('actareunion/search', ['as' => 'actareunion/search', 'uses'=>'ActareunionController@search']);
//ruta para realizar actualizacion de registros.
Route::post('actareunion/update', ['as' => 'actareunion/update', 'uses'=>'ActareunionController@update']);

proyecto/app/Models/Aprendiz.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Aprendiz extends Model
{
    protected $table = 'aprendizs';
  protected $fillable = ['nombre', 'apellido', 'documento', 'edad', 'curso', 'correo'];
  protected $guarded = ['id'];
}

proyecto/app/Http/Controllers/AprendizController.php
<?php

namespace App\Http\Controllers;

use App\Models\Aprendiz as Aprendiz;

use Illuminate\Http\Request;

use App\Http\Requests;

class AprendizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $aprendizs = Aprendiz::all();
        return \View::make('aprendiz/list',compact('aprendizs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return \View::make('aprendiz/new');
    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $aprendiz = new Aprendiz;
       $aprendiz->nombre = $request->nombre;
       $aprendiz->apellido = $request->apellido;
       $aprendiz->documento = $request->documento;
       $aprendiz->edad = $request->edad;
       $aprendiz->curso = $request->curso;
       $aprendiz->correo = $request->correo;
       $aprendiz->save();
       return redirect('aprendiz');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $aprendiz = Aprendiz::find($id);
        return \View::make('aprendiz/update',compact('aprendiz'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $aprendiz = Aprendiz::find($request->id);
        $aprendiz->nombre = $request->nombre;
        $aprendiz->apellido = $request->apellido;
        $aprendiz->documento = $request->documento;
        $aprendiz->edad = $request->edad;
        $aprendiz->curso = $request->curso;
        $aprendiz->correo = $request->correo;
        $aprendiz->save();
        return redirect('aprendiz');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $aprendiz = Aprendiz::find($id);
        $aprendiz->delete();
        return redirect()->back();
    }
     public function search(Request $request)
    {

    
      $aprendizs = Aprendiz::where('nombre','=',$request->nombre)       
        ->get();
       return \View::make('aprendiz/list',compact('aprendizs'));
    }
}

proyecto/resources/views/aprendiz/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="row">
		<section class="col-md-10 col-md-offset-1">
			{!! Form::open(['route' => 'aprendiz/search', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
				<article class="form-group">
					<label for="exampleInputName2">BUSCAR POR NOMBRE</label>
					<input type="text" class="form-control" name = "nombre" >
					<button type="submit" class="btn btn-default glyphicon glyphicon-search"></button>
					<a href="{{ route('aprendiz.index') }}" class="btn btn-primary">MOSTRAR TODO</a>
					<a href="{{ route('aprendiz.create') }}" class="btn btn-primary">CREAR NUEVO REGISTRO </a>
				</article>
			{!! Form::close() !!}
			<article class="form-group">
				<table class="table table-bordered">
					<tr>
						<th>nombres del estudiante</th>
						<th>apellidos del estudiante</th>
						<th>documento de identidad</th>
						<th>edad</th>
						<th>curso</th>
						<th>correo</th>
					</tr>
					<tbody>

						@foreach($aprendizs as $aprendiz)
							<tr>
								<td>{{ $aprendiz->nombre}}</td>
								<td>{{ $aprendiz->apellido}}</td>
								<td>{{ $aprendiz->documento}}</td>
								<td>{{ $aprendiz->edad}}</td>
								<td>{{ $aprendiz->curso}}</td>
								<td>{{ $aprendiz->correo}}</td>
								<td>
									<a class="btn btn-primary btn-xs" href="{{ route('aprendiz.edit',['id' => $aprendiz->id] )}}" >EDITAR</a>
									<a class="btn btn-danger btn-xs" href="{{ route('aprendiz/destroy',['id' => $aprendiz->id] )}}">ARCHIVAR</a>
								</td>
							</tr>
						@endforeach

					</tbody>
				</table>
			</article>
		</section>
	</section>
@endsection

proyecto/resources/views/aprendiz/new.blade.php
@extends('layouts.app')
@section('content')
<section class="container">
	<section class="row">
		<article class="col-md-10 col-md-offset-1">
			{!! Form::open(['route' => 'aprendiz.store', 'method' => 'post', 'novalidate']) !!}
				<section class="form-group">
					{!! Form::label('nombre', 'nombre') !!}
					{!! Form::text('nombre', null, ['id' => 'nombre','class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('apellido', 'apellido') !!}
					{!! Form::text('apellido', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('documento', 'documento') !!}
					{!! Form::text('documento', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('edad', 'edad') !!}
					{!! Form::text('edad', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('curso', 'curso') !!}
					{!! Form::text('curso', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::label('correo', 'correo') !!}
					{!! Form::text('correo', null,['class' => 'form-control', 'required' => 'required']) !!}
				</section>
				<section class="form-group">
					{!! Form::submit('Enviar', ['class' => 'btn btn-succes ' ] ) !!}
				</section>
			{!! Form::close() !!}
		</article>
	</section>
</section>
@endsection

proyecto/resources/views/aprendiz/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="row">
		<section class="col-md-10 col-md-offset-1">
				{!! Form::model($aprendiz, ['route' => 'aprendiz/update', 'method' => 'put', 'novalidate']) !!}
						{!! Form::hidden('id', $aprendiz->id) !!}
						<article class="form-group">
							{!! Form::label('nombre', 'nombre') !!}
							{!! Form::text('nombre', null, ['class' => 'form-control', 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('apellido', 'apellido') !!}
							{!! Form::text('apellido', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('documento', 'documento') !!}
							{!! Form::text('documento', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('edad', 'edad') !!}
							{!! Form::text('edad', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('curso', 'curso') !!}
							{!! Form::text('curso', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						<article class="form-group">
							{!! Form::label('correo', 'correo') !!}
							{!! Form::text('correo', null, ['class' => 'form-control' , 'required' => 'required']) !!}
						</article>
						
						
						<article class="form-group">
							{!! Form::submit('Enviar', null, ['class' => 'btn btn-success']) !!}
						</article>
				 {!! Form::close() !!}
		</section>
	</section>
@endsection